// <auto-generated />
using Ecommerce.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ecommerce.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210925082421_more seeding")]
    partial class moreseeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ecommerce.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("Ecommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProductTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Keyboard",
                            Description = "PC GAMING KEYBOARD AND GAMING MOUSE COMBO: Includes Redragon RGB Backlit Computer Gaming Keyboard and RGB Backlit Gaming Mouse. ALL-IN-ONE PC GAMER VALUE KIT, Fantastic for Gamers (New Improved Version)",
                            ImageURL1 = "https://m.media-amazon.com/images/I/71uIslKmtoL._AC_SL1500_.jpg",
                            ImageURL2 = "https://m.media-amazon.com/images/I/71H6y1GGbAL._AC_SL1500_.jpg",
                            MainImageURL = "https://m.media-amazon.com/images/I/71kr3WAj1FL._AC_SL1500_.jpg",
                            Name = "Redragon Keyboard",
                            Price = 4000,
                            Stock = 200
                        },
                        new
                        {
                            Id = 2,
                            Category = "Keyboard",
                            Description = "Mini 60% Keyboard: RK61 mini 60% gaming keyboard is a ultra-compact layout with 61 keys makes you a neat desktop with your organized gears on, even folks have nothing to do with Minimalist will dive into its tiny practical design. Tips you might want to know is that keyboard without numpad is most FPS gamers' choice, more spaces left for mouse movements.",
                            ImageURL1 = "https://m.media-amazon.com/images/I/71ji90FcW4L._AC_SL1500_.jpg",
                            ImageURL2 = "https://m.media-amazon.com/images/I/71TYtZyvCrS._AC_SL1500_.jpg",
                            MainImageURL = "https://m.media-amazon.com/images/I/61mBAMckzJL._AC_SL1500_.jpg",
                            Name = "RK ROYAL KLUDGE",
                            Price = 3000,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Category = "CPU",
                            Description = "Ryzen 5 3600 6-Core 3.6GHz (4.2GHz Max Boost) CPU Processor | 500G SSD – Up to 30x Faster Than Traditional HDD NVIDIA GeForce GTX 1660 Super 6GB GDDR5 Video Card | 16 GB Gaming Memory DDR4 3000 with Heat Spreader | Windows 10 Home 64 - bit",
                            ImageURL1 = "https://m.media-amazon.com/images/I/71kwAe2O6xL._AC_SL1500_.jpg",
                            ImageURL2 = "https://m.media-amazon.com/images/I/9182gfeh28L._AC_SL1500_.jpg",
                            MainImageURL = "https://m.media-amazon.com/images/I/81Vm7yrdKCL._AC_SL1500_.jpg",
                            Name = "SkyTech Blaze II",
                            Price = 60000,
                            Stock = 50
                        },
                        new
                        {
                            Id = 4,
                            Category = "Games",
                            Description = "Lightning Speed - Harness the power of a custom CPU, GPU, and SSD with Integrated I/O that rewrite the rules of what a PlayStation console can do. Stunning Games - Marvel at incredible graphics and experience new PS5 features.",
                            ImageURL1 = "https://m.media-amazon.com/images/I/619BkvKW35L._SL1500_.jpg",
                            ImageURL2 = "https://m.media-amazon.com/images/I/71v7RDRYBTL._SL1500_.jpg",
                            MainImageURL = "https://m.media-amazon.com/images/I/71vWi5Iuz3L._SL1500_.jpg",
                            Name = "PlayStation 5 Console",
                            Price = 50000,
                            Stock = 400
                        },
                        new
                        {
                            Id = 5,
                            Category = "Headphones",
                            Description = "Built for a new generation - Fine-tuned for 3D Audio on PS5 consoles. Enjoy comfortable gaming with refined earpads and headband strap. Play in style with a sleek design that complements the PS5 console. Available when feature is supported by game.",
                            ImageURL1 = "https://m.media-amazon.com/images/I/71lrh6vzPcL._SL1500_.jpg",
                            ImageURL2 = "https://m.media-amazon.com/images/I/71tU3AxObuL._SL1500_.jpg",
                            MainImageURL = "https://m.media-amazon.com/images/I/610SsJ5aAQL._SL1393_.jpg",
                            Name = "Sony PULSE 3D Wireless Headset",
                            Price = 6000,
                            Stock = 300
                        },
                        new
                        {
                            Id = 6,
                            Category = "Headphones",
                            Description = "Built for a new generation - Fine-tuned for 2D Audio on PS6 consoles. Enjoy comfortable gaming with refined earpads and headband strap. Play in style with a sleek design that complements the PS5 console. Available when feature is supported by game.",
                            ImageURL1 = "https://m.media-amazon.com/images/I/71lrh6vzPcL._SL1500_.jpg",
                            ImageURL2 = "https://m.media-amazon.com/images/I/71tU3AxObuL._SL1500_.jpg",
                            MainImageURL = "https://m.media-amazon.com/images/I/610SsJ5aAQL._SL1393_.jpg",
                            Name = "Sony PULSE 2D Wireless Headset",
                            Price = 2000,
                            Stock = 100
                        },
                        new
                        {
                            Id = 7,
                            Category = "Keyboard",
                            Description = "PC GAMING KEYBOARD AND GAMING MOUSE COMBO: Includes Redragon RGB Backlit Computer Gaming Keyboard and RGB Backlit Gaming Mouse. ALL-IN-ONE PC GAMER VALUE KIT, Fantastic for Gamers (New Improved Version)",
                            ImageURL1 = "https://m.media-amazon.com/images/I/71uIslKmtoL._AC_SL1500_.jpg",
                            ImageURL2 = "https://m.media-amazon.com/images/I/71H6y1GGbAL._AC_SL1500_.jpg",
                            MainImageURL = "https://m.media-amazon.com/images/I/71kr3WAj1FL._AC_SL1500_.jpg",
                            Name = "Redragon Keyboard",
                            Price = 4000,
                            Stock = 200
                        },
                        new
                        {
                            Id = 8,
                            Category = "Keyboard",
                            Description = "Mini 60% Keyboard: RK61 mini 60% gaming keyboard is a ultra-compact layout with 61 keys makes you a neat desktop with your organized gears on, even folks have nothing to do with Minimalist will dive into its tiny practical design. Tips you might want to know is that keyboard without numpad is most FPS gamers' choice, more spaces left for mouse movements.",
                            ImageURL1 = "https://m.media-amazon.com/images/I/71ji90FcW4L._AC_SL1500_.jpg",
                            ImageURL2 = "https://m.media-amazon.com/images/I/71TYtZyvCrS._AC_SL1500_.jpg",
                            MainImageURL = "https://m.media-amazon.com/images/I/61mBAMckzJL._AC_SL1500_.jpg",
                            Name = "RK ROYAL KLUDGE",
                            Price = 3000,
                            Stock = 100
                        },
                        new
                        {
                            Id = 9,
                            Category = "CPU",
                            Description = "Ryzen 5 3600 6-Core 3.6GHz (4.2GHz Max Boost) CPU Processor | 500G SSD – Up to 30x Faster Than Traditional HDD NVIDIA GeForce GTX 1660 Super 6GB GDDR5 Video Card | 16 GB Gaming Memory DDR4 3000 with Heat Spreader | Windows 10 Home 64 - bit",
                            ImageURL1 = "https://m.media-amazon.com/images/I/71kwAe2O6xL._AC_SL1500_.jpg",
                            ImageURL2 = "https://m.media-amazon.com/images/I/9182gfeh28L._AC_SL1500_.jpg",
                            MainImageURL = "https://m.media-amazon.com/images/I/81Vm7yrdKCL._AC_SL1500_.jpg",
                            Name = "SkyTech Blaze II",
                            Price = 60000,
                            Stock = 50
                        },
                        new
                        {
                            Id = 10,
                            Category = "Games",
                            Description = "Lightning Speed - Harness the power of a custom CPU, GPU, and SSD with Integrated I/O that rewrite the rules of what a PlayStation console can do. Stunning Games - Marvel at incredible graphics and experience new PS5 features.",
                            ImageURL1 = "https://m.media-amazon.com/images/I/619BkvKW35L._SL1500_.jpg",
                            ImageURL2 = "https://m.media-amazon.com/images/I/71v7RDRYBTL._SL1500_.jpg",
                            MainImageURL = "https://m.media-amazon.com/images/I/71vWi5Iuz3L._SL1500_.jpg",
                            Name = "PlayStation 5 Console",
                            Price = 50000,
                            Stock = 400
                        },
                        new
                        {
                            Id = 11,
                            Category = "Headphones",
                            Description = "Built for a new generation - Fine-tuned for 3D Audio on PS5 consoles. Enjoy comfortable gaming with refined earpads and headband strap. Play in style with a sleek design that complements the PS5 console. Available when feature is supported by game.",
                            ImageURL1 = "https://m.media-amazon.com/images/I/71lrh6vzPcL._SL1500_.jpg",
                            ImageURL2 = "https://m.media-amazon.com/images/I/71tU3AxObuL._SL1500_.jpg",
                            MainImageURL = "https://m.media-amazon.com/images/I/610SsJ5aAQL._SL1393_.jpg",
                            Name = "Sony PULSE 3D Wireless Headset",
                            Price = 6000,
                            Stock = 300
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
