name: .NET
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-2019
    steps:
    
      - name: checkout repo
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - uses: actions/setup-java@v3
      
        with:
          distribution: temurin
          java-version: '11'
          check-latest: true

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Build and Publish package
        run: >
          dotnet build
          dotnet publish -c Release -r win-x64 -o ./publish Ecommerce.sln
